version: "3.7"

services:
  matomo:
    image: ${DOCKER_SERVICE_MATOMO_IMAGE}
    volumes:
     - type: volume
       source: matomo-volume
       target: /var/www/html
       consistency: delegated

  matomo_web:
    image: ${DOCKER_SERVICE_MATOMO_WEB_IMAGE}
    volumes:
      - type: bind
        source: ./conf/matomo_nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        consistency: delegated
      - type: volume
        source: matomo-volume
        target: /var/www/html
        consistency: delegated
    environment:
      - VIRTUAL_HOST
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web.rule=Host(`${MATOMO_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web_secure.rule=Host(`${MATOMO_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web_secure.tls=true"
    networks:
      default:
        aliases:
          - ${MATOMO_DOMAIN}

  matomo_mysql:
    image: ${DOCKER_SERVICE_MATOMO_DB_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD}
      MYSQL_USER: ${MATOMO_DB_USER}
      MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD}
      MYSQL_DATABASE: ${MATOMO_DB_DATABASE}
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d:delegated
      - ./data/matomo_db:/var/lib/mysql:delegated

volumes:
  matomo-volume:
